# Generated by Django 2.0 on 2019-03-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Topic', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('Description', models.TextField(null=True)),
                ('Status', models.TextField(default='Active')),
            ],
        ),
    ]
