# Generated by Django 2.0 on 2019-04-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
