# Generated by Django 2.0 on 2019-03-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Shift',
            field=models.TextField(),
        ),
    ]
