# Generated by Django 2.0 on 2019-03-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190307_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Day_Of_Week',
            field=models.TextField(),
        ),
    ]
