# Generated by Django 2.0 on 2019-03-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190307_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Month',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
