# Generated by Django 2.0 on 2019-03-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190307_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Comments',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Environment',
            field=models.CharField(default='Please select', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Escalated',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='post',
            name='Escalated_Reason',
            field=models.CharField(default='Please select', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Escalated_to',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='False_alarm',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='post',
            name='Host_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Host_Type',
            field=models.CharField(default='Please select', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='If_Others_Please_Specify',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='Incident_type',
            field=models.CharField(default='Please select', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Mode_of_Alert',
            field=models.TextField(default='Manual check'),
        ),
        migrations.AddField(
            model_name='post',
            name='NOC_Engineer',
            field=models.CharField(default='Please select', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Priority',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='post',
            name='Remediation',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='post',
            name='Resolution',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='post',
            name='Resolved_by_Engineer',
            field=models.CharField(default='noc', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='Resolved_by_Team',
            field=models.CharField(default='Please select', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Responsible_Team',
            field=models.CharField(default='Please select', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Source_of_Alert',
            field=models.CharField(default='Please select', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Status',
            field=models.CharField(default='Resolved', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Month',
            field=models.CharField(default='March', max_length=100),
        ),
    ]
