# Generated by Django 2.0 on 2019-03-30 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190312_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Escalated',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Escalated_Reason',
            field=models.CharField(blank=True, default='Please select', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='False_Alarm',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='If_Others_Please_Specify',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Month',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Priority',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='Remediation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Resolution',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Status',
            field=models.CharField(blank=True, default='Resolved', max_length=100, null=True),
        ),
    ]
