# Generated by Django 2.0 on 2019-04-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190330_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Complexity',
        ),
        migrations.AlterField(
            model_name='post',
            name='Year',
            field=models.PositiveSmallIntegerField(db_column='yeer', default=2019),
        ),
    ]
