# Generated by Django 2.0 on 2019-04-25 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190402_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='Complexity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Interval',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Ticket_Number',
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(db_column='dete', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='Day_Of_Week',
            field=models.TextField(db_column='dayofweek', default='Weekday'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Escalated_Reason',
            field=models.CharField(blank=True, db_column='escreason', default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='False_Alarm',
            field=models.TextField(db_column='falsealarm', default='No'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Month',
            field=models.CharField(db_column='menth', default='April', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Priority',
            field=models.CharField(db_column='priority', default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='Responded_Time',
            field=models.CharField(db_column='rtime', default='01:00', max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='Shift',
            field=models.TextField(db_column='shyft', default='apac'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Start_Time',
            field=models.CharField(db_column='stime', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Time_spent',
            field=models.CharField(db_column='wtime', max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='Week',
            field=models.IntegerField(db_column='weekno', default=17, null=True),
        ),
    ]
