# Generated by Django 2.0 on 2019-04-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190425_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Shift',
            field=models.TextField(db_column='shyft', default='emea'),
        ),
    ]
