# Generated by Django 2.0 on 2019-04-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190425_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Shift',
            field=models.TextField(db_column='shyft', default='apac'),
        ),
    ]
