# Generated by Django 2.0 on 2019-05-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20190508_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Alert',
            field=models.CharField(db_column='alertname', default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='General_Health_Check',
            field=models.CharField(db_column='ghcname', default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Task',
            field=models.CharField(db_column='taskname', default='NA', max_length=100, null=True),
        ),
    ]
