# Generated by Django 2.0 on 2019-05-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20190509_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Shift',
            field=models.TextField(blank=True, db_column='shyft', default='EMEA'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Week',
            field=models.CharField(db_column='weekno', default='Week 19', max_length=20, null=True),
        ),
    ]
