# Generated by Django 2.0 on 2019-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20190509_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Day_Of_Week',
            field=models.TextField(db_column='dayofweek', default='Weekend'),
        ),
    ]
