# Generated by Django 2.0 on 2019-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20190512_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(db_column='dete', default='2019-05-15'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Day_Of_Week',
            field=models.TextField(db_column='dayofweek', default='Weekday'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Escalated_to',
            field=models.CharField(blank=True, db_column='escalatedto', default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Week',
            field=models.CharField(db_column='weekno', default='Week 20', max_length=20, null=True),
        ),
    ]
