# Generated by Django 2.0 on 2019-05-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20190515_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Interval',
            field=models.PositiveSmallIntegerField(blank=True, db_column='intrval', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='If_Others_Please_Specify',
            field=models.CharField(blank=True, db_column='others', default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Remediation',
            field=models.TextField(blank=True, db_column='remediation', default='NA', null=True),
        ),
    ]
