# Generated by Django 2.2.1 on 2019-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20190515_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Interval',
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(db_column='dete', default='2019-05-18'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Day_Of_Week',
            field=models.TextField(db_column='dayofweek', default='Weekend'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Mode_of_Alert',
            field=models.TextField(db_column='mode', default='Manual'),
        ),
    ]
