# Generated by Django 2.2.1 on 2019-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20190524_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(db_column='dete', default='2019-05-31'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Shift',
            field=models.TextField(blank=True, db_column='shyft', default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='Week',
            field=models.CharField(db_column='weekno', default='Week 22', max_length=20, null=True),
        ),
    ]
