# Generated by Django 2.2 on 2020-03-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20200316_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(db_column='dete', default='2020-03-18'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Shift',
            field=models.TextField(db_column='shyft', default='APAC'),
        ),
    ]
