# Generated by Django 2.2 on 2021-06-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20200318_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateField(db_column='dete', default='2021-06-09'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Month',
            field=models.CharField(db_column='menth', default='June', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='Week',
            field=models.CharField(db_column='weekno', default='Week 23', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='Year',
            field=models.PositiveSmallIntegerField(db_column='yeer', default=2021),
        ),
    ]
